name: Docker Image CI

on:
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest

    permissions: 
      contents: write 
    #   id-token: write
    steps:
    - uses: actions/checkout@v4
      with: 
       token: ${{ secrets.ACCESS_TOKEN }}
       fetch-depth: 0 # full history so rebase works
    
    - uses: actions/setup-node@v6
    
    - name: install dependencies
      run: npm install
      
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag 286668306968.dkr.ecr.us-east-1.amazonaws.com/simple/nginx:${{ github.sha }}

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v6.0.0
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET }}
        aws-region: us-east-1

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2

    - name: push the image
      run: docker push 286668306968.dkr.ecr.us-east-1.amazonaws.com/simple/nginx:${{ github.sha }}

    - name: Update manifest and push 
      run: | 
        yq eval -i '.spec.template.spec.containers[0].image = "286668306968.dkr.ecr.us-east-1.amazonaws.com/simple/nginx:433788aba81deca57ab8a5569eb6ccfe10c17006"' ./manifests/deploy.yaml 
        git config user.name "Sushmaganda" 
        git config user.email "gsushmareddy2000@gmail.com" 
        git add ./manifests/deploy.yaml 
        git commit -m "updating the latest image" || echo "No changes to commit" 
        
        # Rebase and auto-resolve conflicts by preferring our version of deploy.yaml 
        git pull --rebase origin main || true 
        git checkout --ours ./manifests/deploy.yaml 
        git add ./manifests/deploy.yaml git rebase --continue || true 
        git push origin main
